package rekammedis;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class MasterCariTemplateResume extends javax.swing.JDialog {
				private final DefaultTableModel tabMode;
				private sekuel Sequel=new sekuel();
				private validasi Valid=new validasi();
				private Connection koneksi=koneksiDB.condb();
				private PreparedStatement ps;
				private ResultSet rs;
				private int i;

				/** Creates new form DlgProgramStudi
					* @param parent
					* @param modal */
				public MasterCariTemplateResume(java.awt.Frame parent, boolean modal) {
								super(parent, modal);
								initComponents();

								Object[] row={
												"No", "Nama Template", "Keluhan", "Jalannya Penyakit",
												"Diagnosa Utama", "Diagnosa Sekunder", "Prosedur Utama",
												"Prosedur Sekunder", "Kondisi Pulang", "Obat Pulang"
								};
								tabMode=new DefaultTableModel(null,row){
														@Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
								};
								tbDokter.setModel(tabMode);

								tbDokter.setPreferredScrollableViewportSize(new Dimension(800,800));
								tbDokter.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

								for (i = 0; i < 10; i++) {
												TableColumn column = tbDokter.getColumnModel().getColumn(i);
												if(i==0){
																column.setPreferredWidth(70);
												}else if(i==1){
																column.setPreferredWidth(180);
												}else if(i==2){
																column.setPreferredWidth(200);
												}else if(i==3){
																column.setPreferredWidth(200);
												}else if(i==4){
																column.setPreferredWidth(200);
												}else if(i==5){
																column.setPreferredWidth(200);
												}else if(i==6){
																column.setPreferredWidth(200);
												}else if(i==7){
																column.setPreferredWidth(200);
												}else if(i==8){
																column.setPreferredWidth(150);
												}else if(i==9){
																column.setPreferredWidth(200);
												}
								}
								tbDokter.setDefaultRenderer(Object.class, new WarnaTable());

								Kd.setDocument(new batasInput((byte)5).getKata(Kd));
								TCari.setDocument(new batasInput((byte)100).getKata(TCari));

								if(koneksiDB.CARICEPAT().equals("aktif")){
												TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
																@Override
																public void insertUpdate(DocumentEvent e) {
																				if(TCari.getText().length()>2){
																								tampil();
																				}
																}
																@Override
																public void removeUpdate(DocumentEvent e) {
																				if(TCari.getText().length()>2){
																								tampil();
																				}
																}
																@Override
																public void changedUpdate(DocumentEvent e) {
																				if(TCari.getText().length()>2){
																								tampil();
																				}
																}
												});
								}

								Keluhan.setDocument(new batasInput((int)200).getKata(Keluhan));
								JalannyaPenyakit.setDocument(new batasInput((int)200).getKata(JalannyaPenyakit));
								DiagnosaUtama.setDocument(new batasInput((int)100).getKata(DiagnosaUtama));
								DiagnosaSekunder1.setDocument(new batasInput((int)100).getKata(DiagnosaSekunder1));
								ProsedurUtama.setDocument(new batasInput((int)100).getKata(ProsedurUtama));
								ProsedurSekunder1.setDocument(new batasInput((int)100).getKata(ProsedurSekunder1));
								Obat2an.setDocument(new batasInput((int)200).getKata(Obat2an));
				}

				/** This method is called from within the constructor to
					* initialize the form.
					* WARNING: Do NOT modify this code. The content of this method is
					* always regenerated by the Form Editor.
					*/
				@SuppressWarnings("unchecked")
				// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
				private void initComponents() {

								internalFrame1 = new widget.InternalFrame();
								TabRawat = new javax.swing.JTabbedPane();
								internalFrame2 = new widget.InternalFrame();
								scrollInput = new widget.ScrollPane();
								FormInput = new widget.PanelBiasa();
								label12 = new widget.Label();
								Kd = new widget.TextBox();
								label13 = new widget.Label();
								NamaTemplate = new widget.TextBox();
								jSeparator1 = new javax.swing.JSeparator();
								label34 = new widget.Label();
								Keluhan = new widget.TextBox();
								label17 = new widget.Label();
								JalannyaPenyakit = new widget.TextBox();
								label18 = new widget.Label();
								DiagnosaUtama = new widget.TextBox();
								label19 = new widget.Label();
								DiagnosaSekunder1 = new widget.TextBox();
								label20 = new widget.Label();
								ProsedurUtama = new widget.TextBox();
								label21 = new widget.Label();
								ProsedurSekunder1 = new widget.TextBox();
								label22 = new widget.Label();
								Kondisi = new widget.ComboBox();
								label23 = new widget.Label();
								Obat2an = new widget.TextBox();
								internalFrame3 = new widget.InternalFrame();
								Scroll = new widget.ScrollPane();
								tbDokter = new widget.Table();
								panelGlass9 = new widget.panelisi();
								label9 = new widget.Label();
								TCari = new widget.TextBox();
								BtnCari = new widget.Button();
								BtnAll = new widget.Button();
								panelGlass8 = new widget.panelisi();
								BtnSimpan = new widget.Button();
								BtnBatal = new widget.Button();
								BtnHapus = new widget.Button();
								BtnEdit = new widget.Button();
								label10 = new widget.Label();
								LCount = new widget.Label();
								BtnKeluar = new widget.Button();

								setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
								setUndecorated(true);
								setResizable(false);

								internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Master Template Resume Inap]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
								internalFrame1.setName("internalFrame1"); // NOI18N
								internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

								TabRawat.setBackground(new java.awt.Color(254, 255, 254));
								TabRawat.setForeground(new java.awt.Color(50, 50, 50));
								TabRawat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
								TabRawat.setName("TabRawat"); // NOI18N
								TabRawat.addMouseListener(new java.awt.event.MouseAdapter() {
												public void mouseClicked(java.awt.event.MouseEvent evt) {
																TabRawatMouseClicked(evt);
												}
								});

								internalFrame2.setBorder(null);
								internalFrame2.setName("internalFrame2"); // NOI18N
								internalFrame2.setLayout(new java.awt.BorderLayout(1, 1));

								scrollInput.setName("scrollInput"); // NOI18N
								scrollInput.setPreferredSize(new java.awt.Dimension(694, 400));

								FormInput.setBackground(new java.awt.Color(255, 255, 255));
								FormInput.setBorder(null);
								FormInput.setName("FormInput"); // NOI18N
								FormInput.setPreferredSize(new java.awt.Dimension(694, 380));
								FormInput.setLayout(null);

								label12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label12.setText("No.Template :");
								label12.setName("label12"); // NOI18N
								label12.setPreferredSize(new java.awt.Dimension(75, 23));
								FormInput.add(label12);
								label12.setBounds(10, 10, 100, 23);

								Kd.setName("Kd"); // NOI18N
								Kd.setPreferredSize(new java.awt.Dimension(207, 23));
								Kd.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																KdKeyPressed(evt);
												}
								});
								FormInput.add(Kd);
								Kd.setBounds(120, 10, 100, 23);

								label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label13.setText("Nama Template :");
								label13.setName("label13"); // NOI18N
								label13.setPreferredSize(new java.awt.Dimension(75, 23));
								FormInput.add(label13);
								label13.setBounds(230, 10, 100, 23);

								NamaTemplate.setName("NamaTemplate"); // NOI18N
								NamaTemplate.setPreferredSize(new java.awt.Dimension(207, 23));
								NamaTemplate.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																NamaTemplateKeyPressed(evt);
												}
								});
								FormInput.add(NamaTemplate);
								NamaTemplate.setBounds(340, 10, 340, 23);

								jSeparator1.setBackground(new java.awt.Color(239, 244, 234));
								jSeparator1.setForeground(new java.awt.Color(239, 244, 234));
								jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 244, 234)));
								jSeparator1.setName("jSeparator1"); // NOI18N
								FormInput.add(jSeparator1);
								jSeparator1.setBounds(0, 40, 750, 1);

								label34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label34.setText("Keluhan :");
								label34.setName("label34"); // NOI18N
								label34.setPreferredSize(new java.awt.Dimension(70, 23));
								FormInput.add(label34);
								label34.setBounds(10, 50, 100, 23);

								Keluhan.setName("Keluhan"); // NOI18N
								Keluhan.setPreferredSize(new java.awt.Dimension(80, 23));
								Keluhan.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																KeluhanKeyPressed(evt);
												}
								});
								FormInput.add(Keluhan);
								Keluhan.setBounds(120, 50, 560, 23);

								label17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label17.setText("Jalannya Penyakit :");
								label17.setName("label17"); // NOI18N
								label17.setPreferredSize(new java.awt.Dimension(70, 23));
								FormInput.add(label17);
								label17.setBounds(10, 80, 100, 23);

								JalannyaPenyakit.setName("JalannyaPenyakit"); // NOI18N
								JalannyaPenyakit.setPreferredSize(new java.awt.Dimension(80, 23));
								JalannyaPenyakit.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																JalannyaPenyakitKeyPressed(evt);
												}
								});
								FormInput.add(JalannyaPenyakit);
								JalannyaPenyakit.setBounds(120, 80, 560, 23);

								label18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label18.setText("Diagnosa Utama :");
								label18.setName("label18"); // NOI18N
								label18.setPreferredSize(new java.awt.Dimension(70, 23));
								FormInput.add(label18);
								label18.setBounds(10, 110, 100, 23);

								DiagnosaUtama.setName("DiagnosaUtama"); // NOI18N
								DiagnosaUtama.setPreferredSize(new java.awt.Dimension(80, 23));
								DiagnosaUtama.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																DiagnosaUtamaKeyPressed(evt);
												}
								});
								FormInput.add(DiagnosaUtama);
								DiagnosaUtama.setBounds(120, 110, 560, 23);

								label19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label19.setText("Diagnosa Sekunder:");
								label19.setName("label19"); // NOI18N
								label19.setPreferredSize(new java.awt.Dimension(70, 23));
								FormInput.add(label19);
								label19.setBounds(10, 140, 110, 23);

								DiagnosaSekunder1.setName("DiagnosaSekunder1"); // NOI18N
								DiagnosaSekunder1.setPreferredSize(new java.awt.Dimension(80, 23));
								DiagnosaSekunder1.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																DiagnosaSekunder1KeyPressed(evt);
												}
								});
								FormInput.add(DiagnosaSekunder1);
								DiagnosaSekunder1.setBounds(120, 140, 560, 23);

								label20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label20.setText("Prosedur Utama :");
								label20.setName("label20"); // NOI18N
								label20.setPreferredSize(new java.awt.Dimension(70, 23));
								FormInput.add(label20);
								label20.setBounds(10, 170, 100, 23);

								ProsedurUtama.setName("ProsedurUtama"); // NOI18N
								ProsedurUtama.setPreferredSize(new java.awt.Dimension(80, 23));
								ProsedurUtama.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																ProsedurUtamaKeyPressed(evt);
												}
								});
								FormInput.add(ProsedurUtama);
								ProsedurUtama.setBounds(120, 170, 560, 23);

								label21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label21.setText("Prosedur Sekunder :");
								label21.setName("label21"); // NOI18N
								label21.setPreferredSize(new java.awt.Dimension(70, 23));
								FormInput.add(label21);
								label21.setBounds(10, 200, 110, 23);

								ProsedurSekunder1.setName("ProsedurSekunder1"); // NOI18N
								ProsedurSekunder1.setPreferredSize(new java.awt.Dimension(80, 23));
								ProsedurSekunder1.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																ProsedurSekunder1KeyPressed(evt);
												}
								});
								FormInput.add(ProsedurSekunder1);
								ProsedurSekunder1.setBounds(120, 200, 560, 23);

								label22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label22.setText("Kondisi Pulang :");
								label22.setName("label22"); // NOI18N
								label22.setPreferredSize(new java.awt.Dimension(70, 23));
								FormInput.add(label22);
								label22.setBounds(10, 230, 100, 23);

								Kondisi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sembuh", "Membaik", "Belum Sembuh", "Meninggal", "Dirujuk" }));
								Kondisi.setName("Kondisi"); // NOI18N
								Kondisi.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																KondisiKeyPressed(evt);
												}
								});
								FormInput.add(Kondisi);
								Kondisi.setBounds(120, 230, 150, 23);

								label23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								label23.setText("Obat Pulang :");
								label23.setName("label23"); // NOI18N
								label23.setPreferredSize(new java.awt.Dimension(70, 23));
								FormInput.add(label23);
								label23.setBounds(10, 260, 100, 23);

								Obat2an.setName("Obat2an"); // NOI18N
								Obat2an.setPreferredSize(new java.awt.Dimension(80, 23));
								Obat2an.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																Obat2anKeyPressed(evt);
												}
								});
								FormInput.add(Obat2an);
								Obat2an.setBounds(120, 260, 560, 23);

								scrollInput.setViewportView(FormInput);

								internalFrame2.add(scrollInput, java.awt.BorderLayout.CENTER);

								TabRawat.addTab("Input Template", internalFrame2);

								internalFrame3.setBorder(null);
								internalFrame3.setName("internalFrame3"); // NOI18N
								internalFrame3.setLayout(new java.awt.BorderLayout(1, 1));

								Scroll.setName("Scroll"); // NOI18N
								Scroll.setOpaque(true);
								Scroll.setPreferredSize(new java.awt.Dimension(452, 200));

								tbDokter.setAutoCreateRowSorter(true);
								tbDokter.setModel(new javax.swing.table.DefaultTableModel(
												new Object [][] {
																{},
																{},
																{},
																{}
												},
												new String [] {

												}
								));
								tbDokter.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
								tbDokter.setName("tbDokter"); // NOI18N
								tbDokter.addMouseListener(new java.awt.event.MouseAdapter() {
												public void mouseClicked(java.awt.event.MouseEvent evt) {
																tbDokterMouseClicked(evt);
												}
								});
								tbDokter.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																tbDokterKeyPressed(evt);
												}
								});
								Scroll.setViewportView(tbDokter);

								internalFrame3.add(Scroll, java.awt.BorderLayout.CENTER);

								panelGlass9.setName("panelGlass9"); // NOI18N
								panelGlass9.setPreferredSize(new java.awt.Dimension(44, 44));
								panelGlass9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

								label9.setText("Key Word :");
								label9.setName("label9"); // NOI18N
								label9.setPreferredSize(new java.awt.Dimension(70, 23));
								panelGlass9.add(label9);

								TCari.setName("TCari"); // NOI18N
								TCari.setPreferredSize(new java.awt.Dimension(530, 23));
								TCari.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																TCariKeyPressed(evt);
												}
								});
								panelGlass9.add(TCari);

								BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
								BtnCari.setMnemonic('1');
								BtnCari.setToolTipText("Alt+1");
								BtnCari.setName("BtnCari"); // NOI18N
								BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
								BtnCari.addActionListener(new java.awt.event.ActionListener() {
												public void actionPerformed(java.awt.event.ActionEvent evt) {
																BtnCariActionPerformed(evt);
												}
								});
								BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																BtnCariKeyPressed(evt);
												}
								});
								panelGlass9.add(BtnCari);

								BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
								BtnAll.setMnemonic('M');
								BtnAll.setToolTipText("Alt+M");
								BtnAll.setName("BtnAll"); // NOI18N
								BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
								BtnAll.addActionListener(new java.awt.event.ActionListener() {
												public void actionPerformed(java.awt.event.ActionEvent evt) {
																BtnAllActionPerformed(evt);
												}
								});
								BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																BtnAllKeyPressed(evt);
												}
								});
								panelGlass9.add(BtnAll);

								internalFrame3.add(panelGlass9, java.awt.BorderLayout.PAGE_END);

								TabRawat.addTab("Data Template", internalFrame3);

								internalFrame1.add(TabRawat, java.awt.BorderLayout.CENTER);

								panelGlass8.setName("panelGlass8"); // NOI18N
								panelGlass8.setPreferredSize(new java.awt.Dimension(44, 54));
								panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

								BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16i.png"))); // NOI18N
								BtnSimpan.setMnemonic('S');
								BtnSimpan.setText("Simpan");
								BtnSimpan.setToolTipText("Alt+S");
								BtnSimpan.setName("BtnSimpan"); // NOI18N
								BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
								BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
												public void actionPerformed(java.awt.event.ActionEvent evt) {
																BtnSimpanActionPerformed(evt);
												}
								});
								BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																BtnSimpanKeyPressed(evt);
												}
								});
								panelGlass8.add(BtnSimpan);

								BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
								BtnBatal.setMnemonic('B');
								BtnBatal.setText("Baru");
								BtnBatal.setToolTipText("Alt+B");
								BtnBatal.setName("BtnBatal"); // NOI18N
								BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
								BtnBatal.addActionListener(new java.awt.event.ActionListener() {
												public void actionPerformed(java.awt.event.ActionEvent evt) {
																BtnBatalActionPerformed(evt);
												}
								});
								BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																BtnBatalKeyPressed(evt);
												}
								});
								panelGlass8.add(BtnBatal);

								BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
								BtnHapus.setMnemonic('H');
								BtnHapus.setText("Hapus");
								BtnHapus.setToolTipText("Alt+H");
								BtnHapus.setName("BtnHapus"); // NOI18N
								BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
								BtnHapus.addActionListener(new java.awt.event.ActionListener() {
												public void actionPerformed(java.awt.event.ActionEvent evt) {
																BtnHapusActionPerformed(evt);
												}
								});
								BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																BtnHapusKeyPressed(evt);
												}
								});
								panelGlass8.add(BtnHapus);

								BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
								BtnEdit.setMnemonic('G');
								BtnEdit.setText("Ganti");
								BtnEdit.setToolTipText("Alt+G");
								BtnEdit.setName("BtnEdit"); // NOI18N
								BtnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
								BtnEdit.addActionListener(new java.awt.event.ActionListener() {
												public void actionPerformed(java.awt.event.ActionEvent evt) {
																BtnEditActionPerformed(evt);
												}
								});
								BtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																BtnEditKeyPressed(evt);
												}
								});
								panelGlass8.add(BtnEdit);

								label10.setText("Record :");
								label10.setName("label10"); // NOI18N
								label10.setPreferredSize(new java.awt.Dimension(90, 23));
								panelGlass8.add(label10);

								LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
								LCount.setText("0");
								LCount.setName("LCount"); // NOI18N
								LCount.setPreferredSize(new java.awt.Dimension(70, 23));
								panelGlass8.add(LCount);

								BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
								BtnKeluar.setMnemonic('K');
								BtnKeluar.setText("Keluar");
								BtnKeluar.setToolTipText("Alt+K");
								BtnKeluar.setName("BtnKeluar"); // NOI18N
								BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
								BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
												public void actionPerformed(java.awt.event.ActionEvent evt) {
																BtnKeluarActionPerformed(evt);
												}
								});
								BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
												public void keyPressed(java.awt.event.KeyEvent evt) {
																BtnKeluarKeyPressed(evt);
												}
								});
								panelGlass8.add(BtnKeluar);

								internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

								getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

								pack();
				}// </editor-fold>//GEN-END:initComponents

				private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
								if(evt.getKeyCode()==KeyEvent.VK_ENTER){
												BtnCariActionPerformed(null);
								}else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
												BtnCari.requestFocus();
								}else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
												BtnKeluar.requestFocus();
								}else if(evt.getKeyCode()==KeyEvent.VK_UP){
												tbDokter.requestFocus();
								}
}//GEN-LAST:event_TCariKeyPressed

				private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
								tampil();
}//GEN-LAST:event_BtnCariActionPerformed

				private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
								if(evt.getKeyCode()==KeyEvent.VK_SPACE){
												BtnCariActionPerformed(null);
								}else{
												Valid.pindah(evt, TCari, BtnAll);
								}
}//GEN-LAST:event_BtnCariKeyPressed

				private void tbDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDokterMouseClicked
								if(tabMode.getRowCount()!=0){
												try {
																getData();
												} catch (java.lang.NullPointerException e) {
												}
												if((evt.getClickCount()==2)&&(tbDokter.getSelectedColumn()==0)){
																TabRawat.setSelectedIndex(0);
												}
								}
}//GEN-LAST:event_tbDokterMouseClicked

				private void tbDokterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDokterKeyPressed
								if(tabMode.getRowCount()!=0){
												if((evt.getKeyCode()==KeyEvent.VK_ENTER)||(evt.getKeyCode()==KeyEvent.VK_UP)||(evt.getKeyCode()==KeyEvent.VK_DOWN)){
																try {
																				getData();
																} catch (java.lang.NullPointerException e) {
																}
												}else if(evt.getKeyCode()==KeyEvent.VK_SPACE){
																try {
																				getData();
																				TabRawat.setSelectedIndex(0);
																} catch (java.lang.NullPointerException e) {
																}
												}
								}
}//GEN-LAST:event_tbDokterKeyPressed

				private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
								if(NamaTemplate.getText().trim().equals("")){
												JOptionPane.showMessageDialog(null,"Maaf, Pilih dulu data yang akan Anda hapus dengan menklik data pada tabel...!!!");
												tbDokter.requestFocus();
								}else{
												if(Valid.hapusTabletf(tabMode,Kd,"template_master_resume","no_template")==true){
																if(tbDokter.getSelectedRow()!= -1){
																				tabMode.removeRow(tbDokter.getSelectedRow());
																				LCount.setText(""+tabMode.getRowCount());
																				emptTeks();
																}
												}
								}
}//GEN-LAST:event_BtnHapusActionPerformed

				private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
								if(evt.getKeyCode()==KeyEvent.VK_SPACE){
												BtnHapusActionPerformed(null);
								}else{
												Valid.pindah(evt, BtnBatal, BtnEdit);
								}
}//GEN-LAST:event_BtnHapusKeyPressed

				private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
							if(Kd.getText().trim().equals("")){
												Valid.textKosong(Kd,"No.Template");
								}else if(NamaTemplate.getText().trim().equals("")){
												Valid.textKosong(NamaTemplate,"Nama Template");
								}else if(Keluhan.getText().trim().equals("")){
												Valid.textKosong(Keluhan,"Keluhan");
								}else if(JalannyaPenyakit.getText().trim().equals("")){
												Valid.textKosong(JalannyaPenyakit,"Jalannya Penyakit");
								}else{
												if(Valid.editTabletf(tabMode,"template_master_resume","no_template","?","no_template=?,nama_template=?,keluhan=?,jalannya_penyakit=?,"+
																"diagnosa_utama=?,diagnosa_sekunder=?,prosedur_utama=?,prosedur_sekunder=?,kondisi_pulang=?,obat_pulang=?",11,new String[]{
																Kd.getText(),NamaTemplate.getText(),Keluhan.getText(),JalannyaPenyakit.getText(),
																DiagnosaUtama.getText(),DiagnosaSekunder1.getText(),ProsedurUtama.getText(),
																ProsedurSekunder1.getText(),Kondisi.getSelectedItem().toString(),Obat2an.getText(),
																tbDokter.getValueAt(tbDokter.getSelectedRow(),0).toString()
												})==true){
															tbDokter.setValueAt(Kd.getText(),tbDokter.getSelectedRow(),0);
															tbDokter.setValueAt(NamaTemplate.getText(),tbDokter.getSelectedRow(),1);
															tbDokter.setValueAt(Keluhan.getText(),tbDokter.getSelectedRow(),2);
															tbDokter.setValueAt(JalannyaPenyakit.getText(),tbDokter.getSelectedRow(),3);
															tbDokter.setValueAt(DiagnosaUtama.getText(),tbDokter.getSelectedRow(),4);
															tbDokter.setValueAt(DiagnosaSekunder1.getText(),tbDokter.getSelectedRow(),5);
															tbDokter.setValueAt(ProsedurUtama.getText(),tbDokter.getSelectedRow(),6);
															tbDokter.setValueAt(ProsedurSekunder1.getText(),tbDokter.getSelectedRow(),7);
															tbDokter.setValueAt(Kondisi.getSelectedItem().toString(),tbDokter.getSelectedRow(),8);
															tbDokter.setValueAt(Obat2an.getText(),tbDokter.getSelectedRow(),9);

															emptTeks();
															TabRawat.setSelectedIndex(1);
												}
								}
}//GEN-LAST:event_BtnEditActionPerformed

				private void BtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditKeyPressed
								if(evt.getKeyCode()==KeyEvent.VK_SPACE){
												BtnEditActionPerformed(null);
								}else{
												Valid.pindah(evt, BtnHapus, BtnKeluar);
								}
}//GEN-LAST:event_BtnEditKeyPressed

				private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
								TCari.setText("");
								tampil();
}//GEN-LAST:event_BtnAllActionPerformed

				private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
								if(evt.getKeyCode()==KeyEvent.VK_SPACE){
												BtnAllActionPerformed(null);
								}else{
												Valid.pindah(evt, BtnCari, BtnKeluar);
								}
}//GEN-LAST:event_BtnAllKeyPressed

				private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
							dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

				private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
								if(evt.getKeyCode()==KeyEvent.VK_SPACE){
												dispose();
								}else{Valid.pindah(evt,BtnAll,TCari);}
}//GEN-LAST:event_BtnKeluarKeyPressed

				private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
								if(Kd.getText().trim().equals("")){
												Valid.textKosong(Kd,"No.Template");
								}else if(NamaTemplate.getText().trim().equals("")){
												Valid.textKosong(NamaTemplate,"Nama Template");
								}else if(Keluhan.getText().trim().equals("")){
												Valid.textKosong(Keluhan,"Keluhan");
								}else if(JalannyaPenyakit.getText().trim().equals("")){
												Valid.textKosong(JalannyaPenyakit,"Jalannya Penyakit");
								}else{
												if(Sequel.menyimpantf("template_master_resume","?,?,?,?,?,?,?,?,?,?","No.Template",10,new String[]{
																Kd.getText(),NamaTemplate.getText(),Keluhan.getText(),JalannyaPenyakit.getText(),
																DiagnosaUtama.getText(),DiagnosaSekunder1.getText(),ProsedurUtama.getText(),
																ProsedurSekunder1.getText(),Kondisi.getSelectedItem().toString(),Obat2an.getText()
												})==true){
																tampil();
																emptTeks();
												}
								}
}//GEN-LAST:event_BtnSimpanActionPerformed

				private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
								if(evt.getKeyCode()==KeyEvent.VK_SPACE){
												BtnSimpanActionPerformed(null);
								}else{
												Valid.pindah(evt,Obat2an,BtnBatal);
								}
}//GEN-LAST:event_BtnSimpanKeyPressed

				private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
								emptTeks();
}//GEN-LAST:event_BtnBatalActionPerformed

				private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
								if(evt.getKeyCode()==KeyEvent.VK_SPACE){
												emptTeks();
								}else{Valid.pindah(evt, BtnSimpan, BtnHapus);}
}//GEN-LAST:event_BtnBatalKeyPressed

				private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KdKeyPressed
								Valid.pindah(evt,TCari,NamaTemplate);
				}//GEN-LAST:event_KdKeyPressed

				private void TabRawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabRawatMouseClicked
								if(TabRawat.getSelectedIndex()==1){
												tampil();
								}
				}//GEN-LAST:event_TabRawatMouseClicked

				private void NamaTemplateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaTemplateKeyPressed
								Valid.pindah(evt,Kd,Keluhan);
				}//GEN-LAST:event_NamaTemplateKeyPressed

				private void KeluhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeluhanKeyPressed
								Valid.pindah(evt,NamaTemplate,JalannyaPenyakit);
				}//GEN-LAST:event_KeluhanKeyPressed

				private void JalannyaPenyakitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JalannyaPenyakitKeyPressed
								Valid.pindah(evt,Keluhan,DiagnosaUtama);
				}//GEN-LAST:event_JalannyaPenyakitKeyPressed

				private void DiagnosaUtamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DiagnosaUtamaKeyPressed
								Valid.pindah(evt,JalannyaPenyakit,DiagnosaSekunder1);
				}//GEN-LAST:event_DiagnosaUtamaKeyPressed

				private void DiagnosaSekunder1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DiagnosaSekunder1KeyPressed
								Valid.pindah(evt,DiagnosaUtama,ProsedurUtama);
				}//GEN-LAST:event_DiagnosaSekunder1KeyPressed

				private void ProsedurUtamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProsedurUtamaKeyPressed
								Valid.pindah(evt,DiagnosaSekunder1,ProsedurSekunder1);
				}//GEN-LAST:event_ProsedurUtamaKeyPressed

				private void ProsedurSekunder1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProsedurSekunder1KeyPressed
								Valid.pindah(evt,ProsedurUtama,Kondisi);
				}//GEN-LAST:event_ProsedurSekunder1KeyPressed

				private void KondisiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KondisiKeyPressed
								Valid.pindah(evt,ProsedurSekunder1,Obat2an);
				}//GEN-LAST:event_KondisiKeyPressed

				private void Obat2anKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Obat2anKeyPressed
								Valid.pindah(evt,Kondisi,BtnSimpan);
				}//GEN-LAST:event_Obat2anKeyPressed


				/**
				* @param args the command line arguments
				*/
				public static void main(String args[]) {
								java.awt.EventQueue.invokeLater(() -> {
												MasterCariTemplateResume dialog = new MasterCariTemplateResume(new javax.swing.JFrame(), true);
												dialog.addWindowListener(new java.awt.event.WindowAdapter() {
																@Override
																public void windowClosing(java.awt.event.WindowEvent e) {
																				System.exit(0);
																}
												});
												dialog.setVisible(true);
								});
				}

				// Variables declaration - do not modify//GEN-BEGIN:variables
				private widget.Button BtnAll;
				private widget.Button BtnBatal;
				private widget.Button BtnCari;
				private widget.Button BtnEdit;
				private widget.Button BtnHapus;
				private widget.Button BtnKeluar;
				private widget.Button BtnSimpan;
				private widget.TextBox DiagnosaSekunder1;
				private widget.TextBox DiagnosaUtama;
				private widget.PanelBiasa FormInput;
				private widget.TextBox JalannyaPenyakit;
				private widget.TextBox Kd;
				private widget.TextBox Keluhan;
				private widget.ComboBox Kondisi;
				private widget.Label LCount;
				private widget.TextBox NamaTemplate;
				private widget.TextBox Obat2an;
				private widget.TextBox ProsedurSekunder1;
				private widget.TextBox ProsedurUtama;
				private widget.ScrollPane Scroll;
				private widget.TextBox TCari;
				private javax.swing.JTabbedPane TabRawat;
				private widget.InternalFrame internalFrame1;
				private widget.InternalFrame internalFrame2;
				private widget.InternalFrame internalFrame3;
				private javax.swing.JSeparator jSeparator1;
				private widget.Label label10;
				private widget.Label label12;
				private widget.Label label13;
				private widget.Label label17;
				private widget.Label label18;
				private widget.Label label19;
				private widget.Label label20;
				private widget.Label label21;
				private widget.Label label22;
				private widget.Label label23;
				private widget.Label label34;
				private widget.Label label9;
				private widget.panelisi panelGlass8;
				private widget.panelisi panelGlass9;
				private widget.ScrollPane scrollInput;
				private widget.Table tbDokter;
				// End of variables declaration//GEN-END:variables

				private void tampil() {
								Valid.tabelKosong(tabMode);
								try{
												ps=koneksi.prepareStatement(
																				"select no_template, nama_template, keluhan, jalannya_penyakit, diagnosa_utama, "+
																				"diagnosa_sekunder, prosedur_utama, prosedur_sekunder, kondisi_pulang, obat_pulang "+
																				"from template_master_resume "+
																				(TCari.getText().equals("")?"":"where no_template like ? or nama_template like ? or keluhan like ? ")+
																				"order by no_template");
												try {
																if(!TCari.getText().trim().equals("")){
																				ps.setString(1,"%"+TCari.getText().trim()+"%");
																				ps.setString(2,"%"+TCari.getText().trim()+"%");
																				ps.setString(3,"%"+TCari.getText().trim()+"%");
																}
																rs=ps.executeQuery();
																while(rs.next()){
																				tabMode.addRow(new Object[]{
																								rs.getString("no_template"),rs.getString("nama_template"),
																								rs.getString("keluhan"),rs.getString("jalannya_penyakit"),
																								rs.getString("diagnosa_utama"),rs.getString("diagnosa_sekunder"),
																								rs.getString("prosedur_utama"),rs.getString("prosedur_sekunder"),
																								rs.getString("kondisi_pulang"),rs.getString("obat_pulang")
																				});
																}
												} catch (Exception e) {
																System.out.println("Notifikasi : "+e);
												} finally{
																if(rs!=null){
																				rs.close();
																}
																if(ps!=null){
																				ps.close();
																}
												}
								}catch(Exception e){
												System.out.println("Notifikasi : "+e);
								}
								LCount.setText(""+tabMode.getRowCount());
				}

				public void emptTeks() {
								Kd.setText("");
								NamaTemplate.setText("");
								Keluhan.setText("");
								JalannyaPenyakit.setText("");
								DiagnosaUtama.setText("");
								DiagnosaSekunder1.setText("");
								ProsedurUtama.setText("");
								ProsedurSekunder1.setText("");
								Kondisi.setSelectedIndex(0);
								Obat2an.setText("");

								Valid.autoNomer("template_master_resume","R",4,Kd);
								TabRawat.setSelectedIndex(0);
								NamaTemplate.requestFocus();
				}

				private void getData() {
								if(tbDokter.getSelectedRow()!= -1){
												Kd.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),0).toString());
												NamaTemplate.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),1).toString());
												Keluhan.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),2).toString());
												JalannyaPenyakit.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),3).toString());
												DiagnosaUtama.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),4).toString());
												DiagnosaSekunder1.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),5).toString());
												ProsedurUtama.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),6).toString());
												ProsedurSekunder1.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),7).toString());
												Kondisi.setSelectedItem(tabMode.getValueAt(tbDokter.getSelectedRow(),8).toString());
												Obat2an.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),9).toString());
								}
				}

				public JTable getTable(){
								return tbDokter;
				}

				public void setTampil(){
							TabRawat.setSelectedIndex(1);
							tampil(); // ensure data is loaded when tab is shown
				}
}
